### ISSUE TITLE
输入语料应该是什么格式呢？

### ISSUE THREAD

**Issue by aluminumbox** [Htiango/KATE-Chinese-Large-Scale#1]
python construct_chinese_train_corpus.py -train [train_path] -o [out_dir] -od [output_dictionary_dir] -threshold [word_freq_threshold] -topn [top_n_words]
这个语句中，tran_path是应该指向一个txt吗，语料应该什么格式呢？

**Comment by Htiango** [comment]
train_path 指向一个训练用的语料文件，格式要求utf-8编码的就行。（后缀名无所谓是啥，具体操作中我是将训练用corpus存为一个后缀为.dat的文件）
